config/routes.rb
Rails.application.routes.draw do
  root to: 'semistatic#index'

  devise_for :users
  resources :games, only: [:create, :update, :index]
  resources :owned_games, only: [:index]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  # Public: If the condition evaluates to true, run the block passed.
  # Otherwise send the user back to either the referrer or the root with an
  # auth message.
  def if_authorized(condition)
    if condition
      yield
    else
      redirect_to request.referrer || root_path,
        alert: 'You are not authorized to perform that action'
    end
  end

  # Public: Checks if a user has already made an action before midnight of
  # today. If so, redirects to either the page they came from or to the root.
  #
  # Accepts a block that'll be executed if the user may execute it.
  def if_user_may
    if user_session['last_action'].nil? || !user_session['last_action'].to_date.today?
      yield
      user_session['last_action'] = Date.current
    else
      redirect_to request.referrer || root_path,
        alert: 'You may only vote or add a game once a day'
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :initialize_games_api
  before_action :authenticate_user!, only: [:create, :update]

  def index
    @games = @games_api.pending_games
  end

  def create
    begin
      if_user_may do
        @games_api.add_game(params[:game][:title])
        redirect_to games_path, notice: 'Game added successfully'
      end
    rescue GamesAPI::DuplicateGameException
      redirect_to games_path, alert: 'That game already exists in the API' 
    rescue GamesAPI::EmptyGameException
      redirect_to games_path, alert: 'The game title is blank'
    rescue GamesAPI::WeekendException
      redirect_to games_path, alert: 'You may not add a game on the weekend'
    end
  end

  def update
    if params[:game_action].nil?
      redirect_to games_path, alert: 'One or more parameters blank.'
    end

    if params[:game_action] == 'vote'
      if_user_may { add_vote(params[:id]) }
    elsif params[:game_action] == 'gotit'
      set_gotit(params[:id])
    end
  end

  private

  def initialize_games_api
    @games_api = GamesAPI.new
  end

  def add_vote(id)
    begin
      @games_api.add_vote(params[:id])
      redirect_to games_path, notice: 'Thanks for voting!'
    rescue GamesAPI::WeekendException
      redirect_to games_path, alert: (
        'You may not vote on games on the weekend'
      )
    end
  end

  def set_gotit(id)
    if_authorized(current_user.is_superuser) do
      @games_api.set_got_it(params[:id])
      redirect_to owned_games_path, notice: 'This game is now marked as owned'
    end
  end
end

app/controllers/owned_games_controller.rb
class OwnedGamesController < ApplicationController
  before_action :initialize_games_api

  def index
    @games = @games_api.owned_games
  end

  private

  def initialize_games_api
    @games_api = GamesAPI.new
  end
end

app/controllers/semistatic_controller.rb
class SemistaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<% provide(:title, 'Pending Games') %>
<% provide(:games_active, true) %>

<% if @games.empty? %>
  <div class="row">
    <div class="small-12 columns">
      <h1>No games yet! <% if !user_signed_in? %>Log in to add some!<% end %></h1>
    </div>
  </div>
<% end %>

<% if user_signed_in? %>
  <div class="row">
    <div class="small-12 columns">
      <%= form_tag(games_path, method: :post) do %>
        <div class="row collapse">
          <div class="small-10 columns">
            <%= text_field_tag 'game[title]', '', placeholder: 'Add a New Game Title' %>
          </div>
          <div class="small-2 columns">
            <%= submit_tag 'Add game', class: 'button postfix' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<% unless @games.empty? %>
  <div class="row">
    <div class="small-12 columns">
      <table class="games-table">
        <thead>
          <th>Game Title</th>
          <th>Votes</th>
          <% if user_signed_in? %>
            <th>Vote</th>
            <% if current_user.is_superuser %>
              <th>Mark as Owned</th>
            <% end %>
          <% end %>
        </thead>
        <% @games.each do |game| %>
          <tr>
            <td>
              <%= game.title %>
            </td>
            <td><%= game.votes %></td>
            <% if user_signed_in? %>
              <td><%= link_to 'Vote!', game_path(game.id, game_action: :vote), method: :put %></td>
              <% if current_user.is_superuser %>
                <td><%= link_to 'Mark as Owned', game_path(game.id, game_action: :gotit), method: :put %></td>
              <% end %>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav data-topbar class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to 'Xbox Voterator', root_path %></h1>
        </li>
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">
        <ul class="left">
          <li <% if content_for?(:games_active) %>class="active"<% end %>><%= link_to 'Games', games_path %></li>
          <li <% if content_for?(:owned_games_active) %>class="active"<% end %>><%= link_to 'Owned Games', owned_games_path %></li>
        </ul>
      </section>

      <section class="top-bar-section">
        <ul class="right">
          <li class="has-form">
            <ul class="button-group round">
              <% if !user_signed_in? %>
                <li>
                  <%= link_to 'Sign In', user_session_path, class: 'button secondary' %>
                </li>
                <li>
                  <%= link_to 'Sign Up', new_user_registration_path, class: 'button secondary' %>
                </li>
              <% else %>
                <li>
                  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'button' %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>
      </section>
    </nav>
    <div class="add-padding">
      <div class="row">
        <% if notice %>
          <div class="small-12 columns">
            <div data-alert class="alert-box success"><%= notice %><a href="#" class="close">&times;</a></div>
          </div>
        <% end %>
        <% if alert %>
          <div class="small-12 columns">
            <div data-alert class="small-12 columns alert alert-box"> <%= alert %><a href="#" class="close">&times;</a></div>
          </div>
        <% end %>
      </div>
    </div>

    <section class="content">
      <%= yield %>
      <%= javascript_include_tag "application" %>
    </section>
  </body>
</html>

app/views/owned_games/index.html.erb
<% provide(:title, 'Owned Games') %>
<% provide(:owned_games_active, true) %>

<div class="row">
  <div class="small-12 columns">
    <% if @games.empty? %>
      <h1>We don't own any games yet!</h1>
    <% else %>
      <h1>Owned Games</h1>
    <% end %>
  </div>
</div>

<% if !@games.empty? %>
  <div class="row">
    <div class="small-12 columns">
      <table class="games-table">
        <thead>
          <th>Game Title</th>
        </thead>
        <% @games.each do |game| %>
          <tr>
            <td><%= game.title %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
<% end %>

app/views/semistatic/index.html.erb
<% provide(:title, 'XBox Voterator') %>
<section class="row">
    <div class="small-12 columns">
        <h1>XBox Voterator</h1>
        <p>Prepare to voterate some xbox games!</p>
    </div>
</section>